package staruml;

public enum ElementType {
	CLASS, INTERFACE, ASSOCIATION, 
	DIRECT_ASSOCIATION, AGGREGATION, 
	COMPOSITION, GENERALIZATION, 
	DEPENDENCY, ALERT, UPDATE_ATTRIBUTES, 
	UPDATE_OPERATIONS, REALIZATION, 
	END2_MULTIPLICITY, END1_MULTIPLICITY, END1_VISIBILITY,
	END2_VISIBILITY, END1_NAME, END2_NAME, END1_IS_NAVIGABLE, 
	END2_IS_NAVIGABLE, END1_AGGREGATION, END2_AGGREGATION,
	ASSOCIATION_NAME, CLASS_NAME, CLASS_VISIBILITY, 
	CLASS_IS_ABSTRACT, DISABLE, ENABLE;
}
